
// Estilos
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 40,
    marginTop: 20,
    textAlign: 'center',
  },
  inputContainer: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  input: {
    width: '80%', 
    height: 50, 
    borderColor: '#ced4da',
    borderWidth: 1, 
    borderRadius: 8, 
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    fontSize: 16,
    marginBottom: 20,
    marginLeft: 25,
  },
  inputList: {
    width: '80%', 
    height: 50, 
    borderColor: '#ced4da',
    borderWidth: 1, 
    borderRadius: 8, 
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    fontSize: 16,
    marginBottom: 20,
    marginLeft: 1,
  },
  addButton: {
    width: 50,
    height: 50,
    backgroundColor: '#007bff',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  loginButton: {
    width: '60%', 
    height: 50, 
    backgroundColor: '#6c757d', 
    justifyContent: 'center', 
    alignItems: 'center', 
    borderRadius: 8,
    marginLeft: 60,
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 18, 
    fontWeight: 'bold', 
  },
  addButtonText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  taskContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ced4da',
  },
  taskText: {
    fontSize: 16,
  },
  removeText: {
    color: '#ff4d4d',
    fontSize: 16,
    fontWeight: 'bold',
  },
  emptyText: {
    textAlign: 'center',
    color: '#6c757d',
    marginTop: 20,
  },
  instructionText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#6c757d',
  },
  logoutButton: {
    color: '#dc3545',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 20,
  },
});
